"""Regenerate the OCI label artifacts consumed by the Docker MCP Toolkit gateway.

The Docker MCP Toolkit gateway (``docker/mcp-gateway``) discovers a server
image by reading the OCI label ``io.docker.server.metadata`` from the image
config — NOT a file inside the image. The label payload must match
``catalog.ImportedServer``:

* ``name``, ``type`` and ``tools[]`` are required. Missing required fields
  cause the gateway to reject the image as "not a self-describing image".
* ``command``, ``volumes``, ``user``, ``secrets[]``, ``env[].value`` and
  other runtime-shaping fields are silently dropped (security policy).
* The label is a JSON string, embedded as a single-line ``LABEL`` in the
  Dockerfile.

Three artifacts are kept in sync by this script:

* ``oci-label.json``    — pretty-printed source of truth, checked in.
* ``oci-label.yaml``    — YAML form for human inspection (``cat``-able).
* ``oci-label.inline``  — single-line JSON, copied verbatim into the
                          ``LABEL io.docker.server.metadata="…"``
                          instruction in the ``Dockerfile``.

Inputs:

* ``docs/mcp/percival-weather-mcp/tools.json`` — generated by
  ``uv run python -m percival_weather_mcp.tool_export --registry``.
  Rebuild that file FIRST whenever tool schemas change.
* ``OciLabelSpec`` below — the fixed project metadata (name, title,
  description, icon, env list, registry metadata). Update this dict when
  the project metadata changes.

Usage::

    uv run python scripts/build_oci_label.py           # write in place
    uv run python scripts/build_oci_label.py --check   # exit non-zero on drift

``--check`` is meant for CI: it fails the build if the checked-in artifacts
would diverge from what this script regenerates.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS_JSON = REPO_ROOT / "docs" / "mcp" / "percival-weather-mcp" / "tools.json"
OUTPUT_DIR = REPO_ROOT / "docs" / "mcp" / "percival-weather-mcp"
JSON_OUT = OUTPUT_DIR / "oci-label.json"
YAML_OUT = OUTPUT_DIR / "oci-label.yaml"
INLINE_OUT = OUTPUT_DIR / "oci-label.inline"


class OciLabelSpec:
    """Fixed metadata block embedded in every regenerated OCI label.

    Update this dict when the project metadata changes. The ``tools`` list
    is filled in at runtime from :data:`TOOLS_JSON`.
    """

    NAME: str = "percival-weather-mcp"
    TYPE: str = "server"
    TITLE: str = "Percival Weather, Air Quality and Time"
    DESCRIPTION: str = (
        "Weather, air quality and time MCP server for the percival.OS ecosystem. "
        "Backed entirely by the public Open-Meteo APIs (no API keys required). "
        "Nine tools, three prompts, three static resources and one resource "
        "template via FastMCP. Defaults to stdio so the Docker MCP Toolkit "
        "gateway spawns it drop-in."
    )
    ICON: str = "https://avatars.githubusercontent.com/u/182288589?s=200&v=4"

    ENV: list[dict[str, str]] = [
        {"name": "MCP_TRANSPORT"},
        {"name": "PORT"},
        {"name": "MCP_WEATHER_HOST"},
        {"name": "MCP_WEATHER_AUTH_TOKEN_ENV"},
        {"name": "MCP_WEATHER_HTTP_TIMEOUT"},
        {"name": "MCP_WEATHER_HTTP_MAX_RETRIES"},
        {"name": "MCP_WEATHER_HTTP_BACKOFF_BASE"},
        {"name": "MCP_WEATHER_HTTP_BACKOFF_CAP"},
        {"name": "MCP_WEATHER_HTTP_MAX_CONCURRENCY"},
        {"name": "MCP_WEATHER_RATE_LIMIT_PER_MINUTE"},
        {"name": "MCP_WEATHER_LOG_FORMAT"},
        {"name": "MCP_WEATHER_ENABLE_METRICS"},
        {"name": "MCP_WEATHER_ENABLE_TRACING"},
    ]

    METADATA: dict[str, Any] = {
        "category": "data",
        "tags": [
            "weather",
            "air-quality",
            "time",
            "timezone",
            "open-meteo",
        ],
        "license": "MIT",
        "owner": "bill-kopp-ai-dev",
    }


def build_oci_label(tools: list[dict[str, Any]]) -> dict[str, Any]:
    """Assemble the OCI label payload from a registry-style tools array."""
    return {
        "name": OciLabelSpec.NAME,
        "type": OciLabelSpec.TYPE,
        "title": OciLabelSpec.TITLE,
        "description": OciLabelSpec.DESCRIPTION,
        "icon": OciLabelSpec.ICON,
        "env": OciLabelSpec.ENV,
        "tools": tools,
        "metadata": OciLabelSpec.METADATA,
    }


def load_registry_tools() -> list[dict[str, Any]]:
    """Load the registry-formatted tools list generated by ``tool_export``."""
    raw = json.loads(TOOLS_JSON.read_text(encoding="utf-8"))
    if not isinstance(raw, list):
        raise ValueError(
            f"{TOOLS_JSON} must contain a JSON array (registry tools list); "
            f"got {type(raw).__name__}"
        )
    return raw


def render_outputs(label: dict[str, Any]) -> dict[str, str]:
    """Render the three on-disk artifacts from the in-memory label."""
    return {
        JSON_OUT.name: json.dumps(label, indent=2, ensure_ascii=False) + "\n",
        YAML_OUT.name: yaml.safe_dump(
            label,
            sort_keys=False,
            allow_unicode=True,
            default_flow_style=False,
            width=1000,
        ),
        INLINE_OUT.name: json.dumps(label, separators=(", ", ": "), ensure_ascii=False),
    }


def _read(path: Path) -> str | None:
    return path.read_text(encoding="utf-8") if path.is_file() else None


def _diff_outputs(rendered: dict[str, str]) -> list[str]:
    mismatches: list[str] = []
    for filename, content in rendered.items():
        on_disk = _read(OUTPUT_DIR / filename)
        if on_disk is None:
            mismatches.append(f"missing: {filename}")
            continue
        if on_disk != content:
            mismatches.append(f"drift: {filename}")
    return mismatches


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero when checked-in artifacts would change.",
    )
    args = parser.parse_args(argv)

    tools = load_registry_tools()
    label = build_oci_label(tools)
    rendered = render_outputs(label)

    if args.check:
        mismatches = _diff_outputs(rendered)
        if mismatches:
            print(
                "OCI label drift detected — run `uv run python scripts/build_oci_label.py`:",
                file=sys.stderr,
            )
            for entry in mismatches:
                print(f"  - {entry}", file=sys.stderr)
            return 1
        print("OCI label artifacts match the regenerator output.")
        return 0

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for filename, content in rendered.items():
        (OUTPUT_DIR / filename).write_text(content, encoding="utf-8")
        print(f"wrote {OUTPUT_DIR / filename}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
